


platform :ios, '7.0'
target 'CreditPlatform' do
pod 'AFNetworking', '~> 3.1.0'

pod 'SDAutoLayout', '~> 2.1.3'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.1'


pod 'FMDB', '~> 2.6.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'MBProgressHUD+BWMExtension', '~> 1.0.1'

pod 'MJExtension', '~> 3.0.10'

pod 'MBProgressHUD+BWMExtension', '~> 1.0.1'

pod 'RTRootNavigationController', '~> 0.5.15'
end
