# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane



# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.14.2"

default_platform :ios

platform :ios do
 
  # 
  desc "Creating a code signing certificate and provisioning profile"
  # 
  lane :provision do
    # 
    produce(
      app_name: 'AD_Demo',
      language: 'zh-Hans',
      app_version: '1.0',
      sku: 'com.3code.ADDemo.Test'
    )
    # 
    cert
    # 
    sigh(force: true)
  end
 
  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end



desc "Upload to App Store and submit for review"
  lane :upload do
    deliver(
      submit_for_review: true
    )
  end

desc "Provision, take screenshots, build and upload to App Store"
  lane :do_everything do
    provision
    screenshot
    build
    upload
  end

  
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
