# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
#   "iPad Pro (12.9 inch)",
#   "iPad Pro (9.7 inch)",
#   "Apple TV 1080p"
# ])

devices([
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus"
])

languages([
  "zh-Hans"
])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
