# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios


platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods(repo_update: false)
    
  end


 # desc "Runs all the tests"
 # lane :test do
 #   scan
 # end



 # desc "Submit a new Beta Build to Apple TestFlight"
 # desc "This will also make sure the profile is up to date"
 # lane :beta do
 #   # match(type: "appstore") # more information: https://codesigning.guide
 #   gym # Build your app - more options available
 #   pilot
#
 #   # sh "your_script.sh"
 #   # You can also use other beta testing services here (run `fastlane actions`)
 # end



 # desc "Deploy a new version to the App Store"
 # lane :release do
 #   # match(type: "appstore")
 #   # snapshot
 #   gym # Build your app - more options available
 #   deliver(force: true)
 #   # frameit
 # end

#蒲公英
lane :beta do
  #cocoapods(repo_update: false)
  gym(use_legacy_build_api: true)
  pgyer(api_key: "512292feaae56ec75625f85227f55d9b", user_key: "d4a73da0e5a0386a5737ee70f5cbd094")
end



  # 创建证书
  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    produce(
      app_name: '立木征信',
      language: 'zh-Hans',
      app_version: '2.0.0',
      sku: 'com.99baozi.LiMuZhengXin'
    )
    cert
    sigh(force: true)
  end


  # 创建 IPA
  desc "Create ipa"
    lane :build do
      increment_build_number
      gym
    end

  # 发布 appstore
  desc "Upload to App Store and submit for review"
    lane :upload do
      deliver(
        submit_for_review: true
      )
    end

  # 全过程
  desc "Provision, take screenshots, build and upload to App Store"
    lane :do_everything do
      provision
      #screenshot
      build
      upload
    end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end



  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
